on: 
  push:
    branches:
      - main

jobs:

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
  
    # Terraform init and apply
    steps:
    - uses: actions/checkout@v2
    
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: false
        args: '-backend=false'
      
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: '.'
        tf_actions_comment: false
        args: -var="environment=dev"

    # Next steps would be apply and destroy with workspace